matrix:
  EXTENSION:
    - extension
    - remote-helper
  steps:
    build:
      when:
        event: [push, pull_request]
      image: node
      commands:
        - cd ${EXTENSION}
        - npm ci
        - npm run lint
        - apt update
        - apt install xvfb xserver-xorg-core
        - xvfb-run npm run test
  