clone:
   - name: git
     image: woodpeckerci/plugin-git
     settings:
        path: /woodpecker/git

matrix:
  EXTENSION:
    - extension
    - remote-helper

steps:
  build:
    when:
      event: [push, pull_request]
    image: nfogh/vscode-ci-test
    commands:
      - cd /woodpecker/git/${EXTENSION}
      - npm ci
      - npm run lint
      - xvfb-run npm run test
      - xvfb-run npm run ui-test
      - npx vsce package
