clone:
   - name: git
     image: woodpeckerci/plugin-git
     settings:
        path: /woodpecker/git

matrix:
  EXTENSION:
    - extension
    - remote-helper

steps:
  deploy:
    when:
      event: tag
    image: node
    environment:
      VSCE_PAT:
        from_secret: vsce_pat
      OVSX_PAT:
        from_secret: ovsx_pat
    commands:
      - cd /woodpecker/git/${EXTENSION}
      - npm ci
      - npm run deploy

depends_on:
 - build